baseURL = "https://rishiraj.dev/"
languageCode = "en"
title = "rishiraj.dev"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "paper"
enableGitInfo = false

author = "Rishiraj Purohit"
copyright = "Copyright © 2019–2023, Rishiraj Purohit; all rights reserved."
paginate = 10
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------

[params]
color = 'linen'

twitter = 'ri5hirajp'
github = 'ri5h'

# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[menu]

# [[menu.main]]
# identifier = "about"
# name = "About"
# url = "/about/"
# weight = 10

[[menu.main]]
identifier = "Personal"
name = "Personal"
url = "/personal/"
weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
